[app]
name = "jntuh-student-helper-bot"

[[services]]
name = "bot-service"
type = "web"

[services.build]
type = "dockerfile"

[services.ports]
port = 3000
protocol = "http"

[services.env]
PORT = "3000"
NODE_ENV = "production"

[services.resources]
memory = "512Mi"
cpu = "0.5"

[services.scaling]
min = 1
max = 1

[services.health_check]
http = { port = 3000, path = "/health" }
